### ISSUE TITLE
Bitte eine kleine Hilfe

### ISSUE THREAD

**Issue by 4444TENSEI** [JonathanXDR/Application-Website-Frontend#62]
Sie haben einen tollen Job gemacht und es ist einfach zu schön. Dies ist die beste persönliche Website, die ich je gesehen habe. Ich möchte wissen, was zu tun ist, wenn ich eine Sprachwechsel-Option für unser Land hinzufügen möchte? Muss ich die JSON-Datei nur direkt bearbeiten? Ich war nicht i18n ausgesetzt, also möchte ich eine Frage stellen

**Comment by JonathanXDR** [comment]
Thank you! Feel free to write in English if that’s easier for you. To retrieve objects and arrays directly from the JSON files, I had to use the vueI18n key (as referenced in i18n.config.ts) in my nuxt.config.ts. Without this, you would only get an abstract syntax tree of translations. I hope this answers your question correctly, but if not, please don’t hesitate to ask for further clarification.

**Comment by 4444TENSEI** [comment]
> Thank you! Feel free to write in English if that’s easier for you. To retrieve objects and arrays directly from the JSON files, I had to use the vueI18n key (as referenced in i18n.config.ts) in my nuxt.config.ts. Without this, you would only get an abstract syntax tree of translations. I hope this answers your question correctly, but if not, please don’t hesitate to ask for further clarification.

Thank you very much. I think I know what to do now
